#!/bin/bash

tput clear
reset

tput cup 3 32
tput setaf 3
echo "CM Setup"
tput sgr0

tput cup 5 32
tput rev 
echo "Main Menu"
tput sgr0

#REPO Sync#
tput cup 7 15
echo "1. Setup CM 10 - 4.1.x"

tput cup 8 15
echo "2. Setup CM 10.1 - 4.2.x"  

tput cup 9 15
echo "0. Exit" 

tput cup 11 15
echo "00. Exit to Main DAET" 

tput bold 
tput cup 20 28
echo -n "Enter Your Choice  "
while read fg
do

###########################
if [ $fg == 1 ]; then
echo "CM Work folder"
Rom/CM_10
###########################
elif [ $fg == 2 ]; then
echo "CM Work folder"
Rom/CM_10.1
###########################
elif [ $fg == 00 ]; then
cd ~/DAET/Rom
. Main
###########################
elif [ $fg == 0 ]; then
exit 1
else
tput cup 19 40
echo "Not a selection from above, Choose again"
fi
echo -n "Enter Your Choice  "
done
