#!/bin/bash

tput clear
reset

tput cup 3 25
tput setaf 3
echo "Paranoid Android Setup"
tput sgr0

tput cup 5 32
tput rev 
echo "Main Menu"
tput sgr0

#REPO Sync#
tput cup 7 15
echo "1. Grab PA Repo (Creates /android/PA folder)"

tput cup 8 15
echo "2. Edit Manifest (Add your device Tree)" 

tput cup 9 15
echo "3. Repo Sync" 

tput cup 10 15
echo "0. Exit"

tput cup 11 15
echo "00. Exit to Main DAET"

tput cup 13 15
tput setaf 3
echo "            Disclaimer:

	        According to PA devs, Add your own: 
			   device tree 
			   kernel tree 
			   hardware source tree
  vendor proprietaries tree in the manifest. (BEFORE the manifest closing tags)"
tput sgr0

tput bold 
tput cup 25 28
echo -n "Enter Your Choice  "
while read fg
do

###########################
if [ $fg == 1 ]; then
echo "PA Work folder"
Rom/PA_repo
else
echo "not here"
fi
###########################
if [ $fg == 2 ]; then
echo "CM Work folder"
Rom/PA_manifest
else
echo "not here"
fi
###########################
if [ $fg == 3 ]; then
Rom/PA_sync
else
echo "not here"
fi
###########################
if [ $fg == 00 ]; then
source ~/DAET/Rom/Main
else
echo "does not work"
fi
###########################
if [ $fg == 0 ]; then
exit 1
else
tput cup 19 40
echo "Not a selection from above, Choose again"
fi
echo -n "Enter Your Choice  "
done
