#!/bin/bash

tput clear

#Repo Sync
if [ ! -d "~/android/PA" ]
then
    cd ~/android/PA
    repo sync -j6
else
    echo "~/android/PA/.repo already exists.  Skipping."
fi

#Return to CM Menu
if [ ! -d "~/AET/Rom" ]
then
	cd ~/AET/Rom
	. CM
else
	echo "Script Malfunctioned"
fi



