#!/bin/bash

tput clear
reset

tput cup 3 32
tput setaf 3
echo "CM Setup"
tput sgr0

tput cup 5 32
tput rev 
echo "Main Menu"
tput sgr0

#REPO Sync#
tput cup 7 15
echo "1. Setup Slimbean 4.2.x (Repo Sync included)" 

tput cup 8 15
echo "0. Exit" 

tput cup 11 15
echo "00. Exit to Main DAET" 

tput bold 
tput cup 20 28
echo -n "Enter Your Choice  "
while read fg
do

###########################
if [ $fg == 1 ]; then
echo "CM Work folder"
Rom/Slimbean
###########################
elif [ $fg == 00 ]; then
cd ~/DAET/Rom
. Main
###########################
elif [ $fg == 0 ]; then
exit 1
else
tput cup 19 40
echo "Not a selection from above, Choose again"
fi
echo -n "Enter Your Choice  "
done
