#!/bin/bash

tput clear

#Making android/cm10 directory
if [ ! -d "~/android/Slimbean" ]
then
    mkdir ~/android
    cd ~/android
    mkdir ~/android/Slimbean	
else
    echo "folder already exists.  Skipping."
fi

#Now...time to grab CM10 repo!
if [ ! -d "~/android/Slimbean" ]
then
    cd ~/android/cm10	
    repo init -u git://github.com/SlimRoms/platform_manifest.git -b jb4.2
else
    echo "folder already exists.  Skipping."
    
fi

#Repo Sync
if [ ! -d "~/android/Slimbean" ]
then
    cd ~/android/Slimbean
    repo sync -j6
else
    echo "folder already exists.  Skipping."
fi

#Return to CM Menu
if [ ! -d "~/AEI/Rom" ]
then
	cd ~/AEI/Rom
	. Slimbean_main
else
	echo "Script Malfunctioned"
fi



