#!/bin/bash

 #
 # Copyright (C) 2012-2013, Ayysir
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 # 

DIR=$(pwd)

while [[ -f $DIR/DAET ]]; do

    if [[ -f $DIR/tools/common ]]; then
      source $DIR/tools/common
    else
      echo "file does not exist"
      exit 1
    fi

    resc=$DIR/scripts

    if [ "$ERROR" != "" ]; then
    echo "Error: $ERROR"
    echo ""
    fi

    echo  "${BRed}Main Menu${Reset}"
    echo  " ------- "
    echo  "1. Ubuntu Setup"
    echo  "2. Archlinux Setup" 
    echo  "3. Update DAET" 
    echo  "0. Exit"
    echo  "Enter your choice " 
    read input

    case $input in
      1)
            if [[ -f $resc/UB ]]; then
              source $resc/UB
            else
              echo "File does not exist"
              reset
              fi
              ;;
      2)
            if [[ -f $resc/AL ]]; then
              source $resc/AL
            else
              echo "File does not exist"
              reset
              fi
              ;;
      3)
            if [[ -f $resc/UPD ]]; then
              source $resc/UPD
            else
              echo "File does not exist"
              reset              
              fi
              ;;

      0)
            reset 
            exit 1
            ;;

      *)
            ERROR=""
            ERROR="Please enter a valid option"
            clear
    esac
done