#!/bin/bash
reset
export VER=v0.2.0
tput cup 0 20
tput setaf 3
echo "Welcome to Android Environment Tool $VER"
tput sgr0

tput cup 1 29
tput setaf 3
echo "by Ayysir"
tput sgr0

tput cup 2 5
echo "--------------------------------------------------------------"
tput sgr0


tput cup 4 30
tput rev 
echo "Main Menu"
tput sgr0

tput cup 5 15
echo "1. Install dependencies (Run this first)"

tput cup 6 15
echo "2. Ubuntu 11.10 users run this second"  

tput cup 7 15
echo "3. Install Android SDK"

tput cup 8 15 
echo "4. Install Android NDK"

tput cup 9 15
echo "5. Install Android Debug Bridge (ADB)"

tput cup 10 15
echo "6. Create 99-android.rules file (Important)"

tput cup 11 15
echo "7. Full Install (1-6)"

tput cup 13 30
tput rev 
echo "Rom Setups"
tput sgr0

tput cup 14 15 
echo "8. Setup CM"

tput cup 15 15 
echo "9. Setup AOKP"

tput cup 16 15
echo "10. Setup Slim Bean"

tput cup 17 15
echo "11. Paranoid Android Setup"

tput cup 19 31
tput rev 
echo "Kernel Building"
tput sgr0

tput cup 20 15
echo "12. Setup Kernel Environment"

tput cup 22 31
tput rev 
echo "Extras"
tput sgr0

tput cup 23 15
echo "13. Tools"

tput cup 24 15
echo "14. System Info"

tput cup 25 15
echo "15. Check for Android SDK Updates"

tput cup 26 15
echo "16. MTP Fix for 12.04 & 12.10 distros"

tput cup 27 15
echo "17. Update Script"

tput cup 28 15
echo "0. Exit"


tput bold 
tput cup 26 26
echo -n "Enter Your Choice  "
tput sgr0
while read fg
do

###########################
if [ $fg == 1 ]; then
echo "Dependencies"
scripts/Dependencies
###########################
elif [ $fg == 2 ]; then
echo "Ubuntu 11.10 users"
scripts/11_10
###########################
elif [ $fg == 3 ]; then
echo "Android SDK"
scripts/SDK
###########################
elif [ $fg == 4 ]; then
echo "Android NDK"
scripts/NDK
###########################
elif [ $fg == 5 ]; then
echo "Android Debug Bridge (ADB)"
scripts/ADB
###########################
elif [ $fg == 6 ]; then
echo "99-android.rules"
scripts/99rules
###########################
elif [ $fg == 7 ]; then
echo "Full Install"
scripts/Dependencies
sleep 2
scripts/11_10
sleep 2
scripts/SDK
sleep 2
scripts/NDK
sleep 2
scripts/ADB
sleep 2
scripts/51rules
###########################
elif [ $fg == 8 ]; then
echo "CM Setup"
Rom/CM
###########################
elif [ $fg == 9 ]; then
echo "AOKP Setup"
Rom/AOKP
###########################
elif [ $fg == 10 ]; then
echo "SlimBean Setup"
Rom/Slimbean_main
###########################
elif [ $fg == 11 ]; then
echo "Paranoid Android Setup"
source ./Rom/PA
###########################
elif [ $fg == 12 ]; then
echo "Kernel"
scripts/Kernel
###########################
elif [ $fg == 13 ]; then
echo "Tools"
scripts/Tools
###########################
elif [ $fg == 14 ]; then
echo "Tools"
scripts/tools/System_info
###########################
elif [ $fg == 15 ]; then
tput bold 
tput cup 28 22
tput setaf 3
echo "Checking for Android SDK Updates"
tput sgr0
scripts/tools/sdk_updates
###########################
elif [ $fg == 16 ]; then
echo "MTP Fix for 12.04 & 12.10"
scripts/tools/mtp_fix
###########################
elif [ $fg == 17 ]; then
tput bold 
tput cup 28 31
tput setaf 3
echo "Updating"
tput sgr0
cd ~/AET
git pull git://github.com/Ayysir/AET.git
############################
elif [ $fg == 0 ]; 
then
	break 1
else
tput bold 
tput cup 28 19
tput setaf 3
echo "Not a Valid selection, Choose again"
tput sgr0
fi
tput bold 
tput cup 30 26
echo -n "Enter Your Choice  "
tput sgr0
done
