#!/bin/bash

echo "Android Folders Backup"
if [ ! -d "~/android/PA" ]
then		
    mkdir ~/android/PA_bkp
    cd ~/android/
    tar -cvzpf PA.tar.gz --exclude='PA_bkp' *PA*
    mv PA.tar.gz PA_bkp
   
   

else
    echo "folder already exists.  Skipping."
fi

#Back to Main Script
if [ ! -f "~/AEI/scripts/Tools" ]
then
	cd ~/AEI/scripts/
	. Tools
else
	echo "Script Malfunctioned"
fi




