#!/bin/bash

echo "Android Folders Backup"
if [ ! -d "~/android/CM10" ]
then		
    mkdir ~/android/CM10_bkp
    cd ~/android/
    tar -cvzpf CM10.tar.gz --exclude='CM10_bkp' *CM10*
    mv CM10.tar.gz CM10_bkp
   
   

else
    echo "folder already exists.  Skipping."
fi

#Back to Main Script
if [ ! -f "~/DAET/scripts/Tools" ]
then
	cd ~/DAET/scripts/
	. Tools
else
	echo "Script Malfunctioned"
fi




