#!/bin/bash
tput bold 
tput cup 0 14
tput setaf 3
read -p "Press [ENTER] to input system password to continue"
tput sgr0

sudo add-apt-repository ppa:langdalepl/gvfs-mtp && sudo apt-get update

tput bold 
tput cup 4 14
tput setaf 3
read -p "You need to reboot Computer Now, [ENTER]"
tput sgr0

#Back to Main Script
if [ ! -f "~/AET/scripts/Tools" ]
then
	cd ~/AET
	. Start
else
	echo "Script Malfunctioned"
fi




