#!/bin/bash

echo "this works 1"
if [ ! -d "~/android/DAET_toolchains" ]
then
    mkdir ~/android/DAET_toolchains
    cd ~/android/DAET_toolchains	
else
    echo "folder already exists.  Skipping."
fi

#Back to Main Script
if [ ! -d "~/DAET/" ]
then
	cd ~/DAET/
	. Start
else
	echo "Script Malfunctioned"
fi




