#!/bin/bash

 #
 # Copyright (C) 2012-2013, Ayysir
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 # 

DIR=$(pwd)
ARH=$DIR/scripts #UBT = UBUNTU, this variable looks for scripts directory in DAET folder

while [[ -f $ARH/AR ]]; do

    if [[ -f $DIR/tools/common ]]; then
		source $DIR/tools/common
	else
		echo "file does not exist"
  		exit 1
	fi

    resc=$DIR/scripts/AR_resc

    if [ "$ERROR" != "" ]; then
    echo "Error: $ERROR"
    echo ""
    fi

  # check if this is a arch distro
  if [ "$OS" = "Arch Linux \r (\l)" ]; then

	echo "${BRed}${ar}Arch Main Menu ${Reset}"
	echo  "        ---------- "
	echo""
	echo  "1. Install Dependencies" 
	echo  "2. Install Android SDK"  
	echo  "3. Install Android Debug Bridge (ADB) & Fastboot"  
	echo  "4. Install 1-3"   
	echo  "5. More"
	echo  "m. Main distro menu"
	echo  "0. Exit" 
  echo "" 
  echo -n "Choice: "
  read input

    case $input in
      1)
            if [[ -f $resc/ar_dependencies ]]; then
              source $resc/ar_dependencies
            else
              echo "File does not exist"
              reset
              fi
              ;;

      2)
            if [[ -f $resc/ar_sdk ]]; then
              source $resc/ar_sdk
            else
              echo "File does not exist"
              reset
              fi
              ;;

      3)
            if [[ -f $resc/ar_adb ]]; then
              source $resc/ar_adb
            else
              echo "File does not exist"
              reset
              fi
              ;;

      4)

            if [[ -f $resc/ar_dependencies ]]; then
              source $resc/ar_dependencies
            else
              echo "File does not exist"
              reset
              fi
              
              sleep 2

            if [[ -f $resc/ar_sdk ]]; then
              source $resc/ar_sdk
            else
              echo "File does not exist"
              reset
              fi
              
              sleep 2

            if [[ -f $resc/ar_adb ]]; then
              source $resc/ar_adb
            else
              echo "File does not exist"
              reset
              fi
              ;;

    6)
            if [[ -f $ARH/More ]]; then
              reset
              source $ARH/More
            else
              echo "File does not exist"
              reset
              fi
              ;;
    "m")
            if [[ -f $DIR/DAET ]]; then
              reset
              source $DIR/DAET
            else
              echo "File does not exist"
              reset
              fi
              ;;


      0)
            reset 
            exit 1
            ;;

      *)
            ERROR=""
            ERROR="Please enter a valid option"
            clear
            ;;
    esac
else
  echo "this is not a archlinux based system"
fi
done