#!/bin/bash

tput clear
reset

tput cup 3 30
tput setaf 3
echo "Kernel Environment"
tput sgr0

tput cup 5 32
tput rev 
echo "Main Menu"
tput sgr0

tput cup 7 15
echo "1. Enivronment Setup"

tput cup 9 15
echo "0. Exit"

tput cup 10 15
echo "00. Exit to Main AEI"

tput bold 
tput cup 11 28
echo -n "Enter Your Choice  "
while read fg
do

###########################
if [ $fg == 1 ]; then
echo "this works 1"
cd ~/AET/scripts/kernel
. Env_Setup
###########################
elif [ $fg == 2 ]; then
echo "this works 1"
tools/bkp_AOKP
###########################
elif [ $fg == 3 ]; then
echo "this works 1"
tools/bkp_SB
###########################
elif [ $fg == 4 ]; then
echo "this works 1"
tools/bkp_CM10
###########################
elif [ $fg == 5 ]; then
echo "this works 1"
tools/bkp_CM10.1
###########################
elif [ $fg == 6 ]; then
echo "this works 1"
tools/bkp_PA
###########################
elif [ $fg == 7 ]; then
echo "this works 1"
tools/bkp_full
###########################
elif [ $fg == 00 ]; then
echo "this works 1"
cd ~/AET/Rom
. Main
###########################
###########################
elif [ $fg == 0 ]; then
exit 1
else
tput cup 19 40
echo "Not a selection from above, Choose again"
fi
echo -n "Enter Your Choice  "
done
