#!/bin/bash

tput clear

#Download and install the Android NDK.
if [ ! -d "/usr/local/android-ndk" ]; then 
	for b in $(  wget -qO- http://developer.android.com/sdk/ndk/index.html | egrep -o "http://dl.google.com[^\"']*linux-x86.tar.bz2"
 ); do wget $b && tar --wildcards --no-anchored -xjvf android-ndk-*-linux-x86.tar.bz2; sudo -v; sudo mv android-ndk-*/ /usr/local/android-ndk; sudo -v; sudo chmod 777 -R /usr/local/android-ndk; rm android-ndk-*-linux-x86.tar.bz2;
	done
else
    echo "Android NDK already installed"
sleep 1
cd ~/AEI
./AEI
fi
#Create Symlink for Dalvik Debug Monitor Server (DDMS)
if [ -f /bin/ddms ] 
then
    sudo -v; sudo rm /bin/ddms; sudo -v; sudo ln -s /usr/local/android-sdk/tools/ddms /bin/ddms
else
    sudo -v; sudo ln -s /usr/local/android-sdk/tools/ddms /bin/ddms
fi

#Back to Main Script
if [ ! -d "~/AEI/" ]
then
	cd ~/AEI/
	. Start
else
	echo "Script Malfunctioned"
fi

