#!/bin/bash

 #
 # Copyright (C) 2012-2013, Ayysir
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #

reset
DIR=$(pwd)

    if [[ -f $DIR/common ]]; then
		source $DIR/common
	else
		echo "file does not exist"
  		exit 1
	fi

if [ "$OS" != "Arch Linux \r (\l)" ]; then
tput bold
tput cup 0 14
tput setaf 3
read -p "Press [ENTER] to input system password to continue"
tput sgr0

sudo add-apt-repository ppa:langdalepl/gvfs-mtp && sudo apt-get update && sudo apt-get upgrade

tput clear
tput bold
tput cup 0 17
tput setaf 3
read -p "You need to reboot Computer Now, [ENTER]"
tput sgr0

#Back to Main Script
cd ..
prev=$PWD

if [[ -f $prev/DAET ]]; then
	source $prev/DAET
else
	echo "script does not exist"
	exit 1
fi
else

echo " This is an archlinux based distro...exiting..."

sleep 2

#Back to Main Script
cd ..
prev=$PWD

if [[ -f $prev/DAET ]]; then
	source $prev/DAET
else
	echo "script does not exist"
	exit 1
fi
fi

