#!/bin/bash
reset 
DIR=$(pwd)

    if [[ -f $DIR/common ]]; then
		source $DIR/common
	else
		echo "file does not exist"
  		exit 1
	fi

if [ "$OS" != "Arch Linux \r (\l)" ]; then
tput bold 
tput cup 0 14
tput setaf 3
read -p "Press [ENTER] to input system password to continue"
tput sgr0

sudo add-apt-repository ppa:langdalepl/gvfs-mtp && sudo apt-get update && sudo apt-get upgrade

tput clear
tput bold 
tput cup 0 17
tput setaf 3
read -p "You need to reboot Computer Now, [ENTER]"
tput sgr0

#Back to Main Script
cd ..
prev=$PWD

if [[ -f $prev/DAET ]]; then
	source $prev/DAET
else
	echo "script does not exist"
	exit 1
fi
else

echo " This is an archlinux based distro...exiting..."

sleep 2

#Back to Main Script
cd ..
prev=$PWD

if [[ -f $prev/DAET ]]; then
	source $prev/DAET
else
	echo "script does not exist"
	exit 1
fi
fi

