#!/bin/bash

 #
 # Copyright (C) 2012-2013, Ayysir
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #

tput clear
DIR=$(pwd)

    if [[ -f $DIR/common ]]; then
		source $DIR/common
	else
		echo "file does not exist"
  		exit 1
	fi

#Download and install the Android NDK.
if [ "$OS" != "Arch Linux \r (\l)" ]; then
if [ ! -d "/usr/local/android-ndk" ]; then
	for b in $(  wget -qO- http://developer.android.com/sdk/ndk/index.html | egrep -o "http://dl.google.com[^\"']*linux-x86.tar.bz2"
 ); do wget $b && tar --wildcards --no-anchored -xjvf android-ndk-*-linux-x86.tar.bz2; sudo -v; sudo mv android-ndk-*/ /usr/local/android-ndk; sudo -v; sudo chmod 777 -R /usr/local/android-ndk; rm android-ndk-*-linux-x86.tar.bz2;
	done
else
    echo "Android NDK already installed"
fi
#Create Symlink for Dalvik Debug Monitor Server (DDMS)
if [ -f /bin/ddms ]
then
    sudo -v; sudo rm /bin/ddms; sudo -v; sudo ln -s /usr/local/android-sdk/tools/ddms /bin/ddms
else
    sudo -v; sudo ln -s /usr/local/android-sdk/tools/ddms /bin/ddms
fi

else
if [ "$OS" != "Arch Linux \r (\l)" ]; then

#Install android-sdk-platform-tools
x=`pacman -Qs android-ndk`
c=android-ndk
if [ -n "$x" ]
 then echo "$c already installed.  Skipping."
  else
	echo "$c was not found, installing..." 2>&1
	sudo pacman -S --noconfirm $c
fi
	else
    echo "Android NDK already installed"
fi
fi

#Back to Main Script
cd ..
prev=$PWD

if [[ -f $prev/DAET ]]; then
	source $prev/DAET
else
	echo "script does not exist"
	exit 1
fi
