#!/bin/bash

 #
 # Copyright (C) 2012-2013, Ayysir
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #

reset

DIR=$(pwd)
resc=$DIR/scripts


    if [[ -f $DIR/common ]]; then
		source $DIR/common
	else
		echo "file does not exist"
  		exit 1
	fi

echo "${BRed}${sysinfo}System Info ${Reset}"
echo  "       ------- "
echo""

echo "Current User =" "${BRed}$USR ${Reset}"

echo "System =" "${BRed}$OS ${Reset}"

echo "Kernerl =" "${BRed}$KER ${Reset}"

echo "Architecture =" "${BRed}$BIT ${Reset}"

echo "GCC Version =" "${BRed}$GCC ${Reset}"


sleep 3
echo""
echo""
echo "Finished?"
read fin

if [[ $fin = y || $fin = Y ]]; then
#below is a bit of a hack but works with no issues
	    cd ..
	    dir=$(pwd)
	    reset
        source $dir/scripts/More
else
	reset
	exit 1
fi
