#!/bin/bash

DIR=$(pwd)
resc=$DIR/scripts

#Create a symlink for libX11
if [ -f "/usr/lib/i386-linux-gnu/libX11.so" ]
then
    sudo -v; sudo rm /usr/lib/i386-linux-gnu/libX11.so; sudo -v; sudo ln -s /usr/lib/i386-linux-gnu/libX11.so.6 /usr/lib/i386-linux-gnu/libX11.so
else
    sudo -v; sudo ln -s /usr/lib/i386-linux-gnu/libX11.so.6 /usr/lib/i386-linux-gnu/libX11.so
fi

#Back to Main Script
if [[ -f $resc/UB ]]; then
	source $resc/UB
else
	echo "script does not exist"
	exit 1
fi


