#!/bin/bash

 #
 # Copyright (C) 2012-2014, Ayysir
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #

tput clear

#Downloads the latest version of 99-android.rules
git clone git@github.com:M0Rf30/android-udev-rules.git -b master
cd android-udev-rules
#wget https://dl.dropboxusercontent.com/u/9621907/51-android.rules
sudo -v; sudo mv -f 51-android.rules /etc/udev/rules.d/

#Back to Main Script
if [ ! -d "~/DAET/" ]
then
	cd ~/DAET/
	. Start
else
	echo "Script Malfunctioned"
fi


