#!/bin/bash

 #
 # Copyright (C) 2012-2013, Ayysir
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #

DIR=$(pwd)
resc=$DIR/scripts

#Create a symlink for Android Debug Bridge (adb)
if [ -f /bin/adb ];
then
    sudo -v; sudo rm /bin/adb; sudo -v; sudo ln -s /usr/local/android-sdk/platform-tools/adb /bin/adb
else
    sudo -v; sudo ln -s /usr/local/android-sdk/platform-tools/adb /bin/adb
fi
#Installing adb!
if [ ! -f "/usr/local/android-sdk/platform-tools/adb" ];
then
	mkdir $HOME/.android; touch $HOME/.android/androidtool.cfg; echo "sdkman.force.http=true" > $HOME/.android/androidtool.cfg; nohup /usr/local/android-sdk/tools/android update sdk > /dev/null 2>&1
else
echo "Android Debug Bridge already detected."
fi

#Back to Main Script
if [[ -f $resc/UB ]]; then
	source $resc/UB
else
	echo "script does not exist"
	exit 1
fi


